bankproject/bankapp/urls.py
from django.urls import path
from . import views
app_name='bankapp'
urlpatterns = [
path('',views.index,name='index'),
]

bankproject/bankproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static



urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include("bankapp.urls")),
    path('credentials/',include("credentials.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bankproject/credentials/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login',views.login,name='login'),
    path('register',views.register,name='register'),
    path('apply',views.apply,name='apply'),
    path('form',views.form,name='form'),
    path('info',views.info,name="info")
]

bankproject/bankapp/models.py
from django.db import models

 #Create your models here.

bankproject/credentials/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    name=models.CharField(max_length=250)
    address=models.TextField()
    phonenumber=models.IntegerField()

    def __str__(self):
        return self.name

bankproject/bankapp/views.py
from django.shortcuts import render
# Create your views here.

def index(request):
    return render(request,"index.html")

bankproject/credentials/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render,redirect
from . models import Person

# Create your views here.
def login(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('apply')
        else:
            messages.info(request,"please register")
            return redirect('register')
    return render(request,"login.html")
def register(request):
    if request.method == 'POST':
        username=request.POST['username']
        password=request.POST['password']
        cpassword=request.POST['password1']
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,"username taken")
                return redirect('register')

            else:
                user=User.objects.create_user(username=username,password=password)

                user.save();
                return redirect('login')


        else:
            messages.info(request,"password not matching")
            return redirect('register')
        return redirect('/')


    return render(request,"register.html")

def apply(request):
    return render(request,"apply.html")
def form(request):
    if request.method=='POST':
        name=request.POST.get('name')
        address=request.POST.get('address')
        phonenumber=request.POST.get('phonenumber')
        person=Person(name=name,address=address,phonenumber=phonenumber)
        person.save()
        return redirect('/credentials/info')
    return render(request,"form.html")
def info(request):
    task1 = Person.objects.all()
    return render(request,"info.html",{'task1':task1})

bankproject/templates/apply.html
{% extends 'base.html' %}
{% block content %}
<br>

<a class="btn btn-success" href="form">Apply The Application</a>
{% endblock %}

bankproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
<div>
 {% block content %}
 {% endblock %}
</div>
    <script src="{% static 'js/popper.min.js' %}" ></script>
    <script src="{% static 'js/bootstrap.min.js' %}" ></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

bankproject/templates/form.html
{% extends 'base.html' %}
{% block content %}
<script>
var subjectObject = {
  "Palakkad": {
    "Alathur": ["dummy"],
    "Vadakkencherry": ["dummy"],
    "Nemmara": ["dummy"]
  },
  "Thrissur": {
    "Koorkencherry": ["dummy"],
    "Chavakkad": ["dummy"],
    "Chalakudy": ["dummy"]

  },
  "Eranakulam":{
  "Edapally":["dummy"],
  "Kalammaseery":["dummy"],
  "Aluva":["dummy"]
  },
  "Kollam":{
  "Thangasserry":["dummy"],
  "Neendakara":["dummy"],
  "Oachira":["dummy"]
  },
  "Wayanad":{
  "Pulpalli":["dummy"],
  "Manathavady":["dummy"],
  "Sulthan bathery":["dummy"]
  }
}
window.onload = function() {
  var subjectSel = document.getElementById("subject");
  var topicSel = document.getElementById("topic");
  for (var x in subjectObject) {
    subjectSel.options[subjectSel.options.length] = new Option(x, x);
  }
  subjectSel.onchange = function() {
    //empty Chapters- and Topics- dropdowns
    topicSel.length = 1;
    //display correct values
    for (var y in subjectObject[this.value]) {
      topicSel.options[topicSel.options.length] = new Option(y, y);
    }
  }
}
</script>
<form name="form1" id="form1" action="" method="POST">
  {% csrf_token %}
    <table>
        <tr>
    <td>
        Name:
    </td>
            <td>
  <input type="text" name="name" placeholder="Enter your Name">
                </td>
            </tr>
        <tr>
            <td>
        Address:
    </td>

    <td>
  <input type="text" name="address" placeholder="Enter your address">
        </td>
            </tr>
        <tr>
    <td>
        Phonenumber:
    </td>
            <td>
  <input type="text" name="phonenumber" placeholder="Enter your phonenumber">
            </td>
        </tr>
    <tr>
            <td>
                Age:
            </td>
            <td>
                <input type="text" placeholder="Enter your Age">
            </td>
        </tr>
        <tr>
            <td>
                Email:
            </td>
            <td>
                <input type="email" placeholder="Enter your mail ID">
            </td>
        </tr>
        <tr>
            <td>
                Gender:
            </td>
            <td>
                <input type="radio" name="Gender">Male
                <input type="radio" name="Gender">Female
            </td>
        </tr>
        <tr>
            <td>
                Date Of Birth:
            </td>
            <td>
                <input type="date">
            </td>
        </tr>
        <tr>
            <td>
                <input type="checkbox"debit>debit
                 <input type="checkbox"credit>credit
                 <input type="checkbox"cheque>cheque
            </td>
        </tr>
        <tr>
            <td>
                Account Type:
            </td>
            <td>
                <select>
                 <option>Please select</option>
                    <option>Savings Account </option>
                    <option>Current Account</option>
                </select>

            </td>
        </tr>
  <tr>
            <td>
              Districts:
            </td>
            <td>
                 <select name="subject" id="subject">
    <option value="" selected="selected">please select</option>
  </select>
            </td>
            <tr>
        <td>
            Branches:
        </td>
        <td>
            <select name="topic" id="topic">
    <option value="" selected="selected">please select</option>
  </select>
        </td>

        </tr>
        <tr>
            <td>
            <input type="submit">
        </td>
            <td>
                <a class="btn btn-danger" href="login">Logout</a>
            </td>
        </tr>

        </table>
</form>

{% endblock %}

bankproject/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="credentials/login">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="credentials/register">Register</a>
        </li>
        <li class="nav-item dropdown {% if 'bankapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Branches
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Palakkad
">Palakkad</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thrissur">Thrissur</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Ernakulam
">Eranakulam</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kollam
">Kollam</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Wayanad_district
">Wayanad</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div>
   <img class="my_image my_image_padding" src="{% static 'img/wssbank.png' %}" alt="bank" width="1250px;">
 </div>
<div>
 &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;<a class="btn btn-primary" href="credentials/login">View More</a>
</div>

{% endblock %}

bankproject/templates/info.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
              {% csrf_token %}
    <h1>application accepted</h1>

            {% for i in task1 %}
                    <h1>{{i.name}}</h1>
                    <p><b>{{i.address}}</b></p>
                    <p><b>{{i.phonenumber}}</b></p>
            {% endfor %}
    <a class="btn btn-success" href="{% url 'bankapp:index' %}">Back to Home</a>
</form>
{% endblock %}

bankproject/templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="text-center">
    <form action="login" method="post">
    {% csrf_token %}
    <h1 class="h3 mb-3">Login</h1>
    <input type="text" name="username" placeholder="enter your username"><br><br>
    <input type="password" name="password" placeholder="enter your password"><br><br>
        <button class="btn btn-lg btn-primary">login</button><br><br>
        <button class="btn btn-lg btn-success">register</button>
</form>
</div>
{% endblock %}

bankproject/templates/register.html
{% extends 'base.html' %}
{% block content %}
<h1>Registration</h1>
<form action="register" method="POST">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Enter your username"><br>
    <input type="password" name="password" placeholder="Enter your password"><br>
    <input type="password" name="password1" placeholder="Confirm your password"><br>
    <input type="submit">
</form>
{% for msg in messages %}
<h2>{{msg}}</h2>
{% endfor %}
{% endblock %}